version: '3.8'

services:
  server:
    image: ${IMAGE_NAME:-x-remove-server}:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:5000"
    volumes:
      - ${HOST_DATA:-/mnt/data}:/data
